### ISSUE TITLE
Arduino code ?

### ISSUE THREAD

**Issue by yo2ldk** [ArmDeveloperEcosystem/audio-spectrogram-example-for-pico#1]
Hello,
 excellent project, congratulations !
 Can you translate please this code to use it with Arduino ?
 I need to add it in my audio project (radio receiver) if I can, to see audio spectrum
 Thank you in advance

**Comment by sandeepmistry** [comment]
Hi @yo2ldk,

Thank you for the positive feedback!

This is most likely out of scope for this project. Just to clarify, are you using the Arduino IDE to program a Raspberry Pi Pico board or are you using a different board?

**Comment by sandeepmistry** [comment]
Closing as out of scope for this project.
