### ISSUE TITLE
Sampling size

### ISSUE THREAD

**Issue by oost** [ArmDeveloperEcosystem/audio-spectrogram-example-for-pico#2]
Great project Sandeep! 

I was wondering why you do the sampling on FFT/2 samples (=128) and not on INPUT_BUFFER_SIZE (=64):
```new_samples_captured = pdm_microphone_read(capture_buffer_q15, FFT_SIZE / 2);```
vs. 
```new_samples_captured = pdm_microphone_read(capture_buffer_q15, INPUT_BUFFER_SIZE);```

You do have an array length guard in the read function so your `samples` variable will be reset to 64 anyway. 
Am I missing something? 

Thank you! 

PS: There is also a small typo with the name of the variable `magnitude`.

**Comment by sandeepmistry** [comment]
Hi @oost,

> PS: There is also a small typo with the name of the variable magnitude.

Thanks corrected in https://github.com/ArmDeveloperEcosystem/audio-spectrogram-example-for-pico/commit/e973efaa546348a86d9471eedf86a922f27311be

> I was wondering why you do the sampling on FFT/2 samples (=128) and not on INPUT_BUFFER_SIZE (=64):
> new_samples_captured = pdm_microphone_read(capture_buffer_q15, FFT_SIZE / 2);
> vs.
> new_samples_captured = pdm_microphone_read(capture_buffer_q15, INPUT_BUFFER_SIZE);
>
> You do have an array length guard in the read function so your samples variable will be reset to 64 anyway.
> Am I missing something?

This is a good question, looking at the code again (after several months), I agree `new_samples_captured = pdm_microphone_read(capture_buffer_q15, INPUT_BUFFER_SIZE);` should be used. Would you like to create a pull request to change this so the code is clearer?
