### ISSUE TITLE
Use smaller display , vertical scrolling not working

### ISSUE THREAD

**Issue by micropicostack** [ArmDeveloperEcosystem/audio-spectrogram-example-for-pico#3]
I had a 240x240 screen laying around and wanted to use that, but the vertical scroll is not working. After digging into the datasheets I found that there is a separate register that can be used to define the scrolling area, by default it did not fit to the 240x240 display. 

My fix would be to add this lien to `st7789.c` but as this is a separate git lib, but still owned by you guys then I would first ask if this could be a solution? 

```c
    uint16_t bfa = ST7789_MAX_HEIGHT - height;

    // VSCRDEF (33h): Vertical Scrolling Definition TFA - VSA - BFA
    st7789_cmd(0x33, (uint8_t[]){ 0x00, 0x00, ((height >> 8) & 0xFF), (height & 0xFF), ((bfa >> 8) & 0xFF), (bfa & 0xFF)}, 6);
```

**Comment by sandeepmistry** [comment]
Hi @micropicostack,

> My fix would be to add this lien to st7789.c but as this is a separate git lib, but still owned by you guys then I would first ask if this could be a solution?

It would be best to propose an API as an issue or pull request in the following repo: https://github.com/ArmDeveloperEcosystem/st7789-library-for-pico
